-- Table: public.org

-- DROP TABLE IF EXISTS public.org;

CREATE TABLE IF NOT EXISTS public.org
(
    org_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    contact_email character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(6) without time zone,
    domain character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    name character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    CONSTRAINT org_pkey PRIMARY KEY (org_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.org
    OWNER to postgres;
	
-- Table: public.roles

-- DROP TABLE IF EXISTS public.roles;

CREATE TABLE IF NOT EXISTS public.roles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    role_name character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.roles
    OWNER to postgres;
	
	
-- Table: public.user_sessions

-- DROP TABLE IF EXISTS public.user_sessions;

CREATE TABLE IF NOT EXISTS public.user_sessions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone,
    is_active boolean,
    refresh_token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id integer,
    CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT uk5ou0u1pqftlypbt1wcsbl5hgh UNIQUE (refresh_token)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_sessions
    OWNER to postgres;

-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    email character varying(255) COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    is_email_verified boolean,
    org_id integer,
    password character varying(255) COLLATE pg_catalog."default",
    role_id integer,
    status smallint,
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_status_check CHECK (status >= 0 AND status <= 2)
)

ALTER TABLE users DROP COLUMN status;

ALTER TABLE users ADD COLUMN status VARCHAR(255);

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;


