spring.application.name=user-org-service

server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:1517/Mercer_Mettl
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=DEBUG
logging.level.com.emp=DEBUG
